name: Ipv4 Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,9,11 * * *'
  push:
    paths-ignore:
      - .github
      - .gitignore
      - LICENSE
      - logo.png

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            branch: bach
            owner: hkwpc2024
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Repository Owner
        id: check_owner
        run: |
          if [ "${{ github.repository_owner }}" != "${{ matrix.owner }}" ]; then
            echo "Repository owner is not ${{ matrix.owner }}. Cancelling the job."
            exit 1
          fi

      - name: GetTime
        run: echo "DATE=$(date +'%Y-%m-%d %H:%M:%S CST' | sed 's/ CST$//')" >> $GITHUB_ENV

      - name: Update Files
        run: |
          rm -f ipv4.m3u && wget https://raw.githubusercontent.com/hkwpc2024/IPTVZD/refs/heads/bach/output/user_result.m3u -O ipv4.m3u

          # å¤®è§†æº
          cat ipv4.m3u > CCTV.m3u
          sed -i -n '/ğŸ“ºä¸­å›½å¤®è§†é¢‘é“/,+1p' CCTV.m3u
          sed -i '/^\s*$/d' CCTV.m3u
          
          # å«è§†æºã€åœ°æ–¹é¢‘é“ã€æ•°å­—é¢‘é“ã€æ¸¯æ¾³å°
          cat ipv4.m3u > CNTV1.m3u && sed -i -n '/ğŸ“¡ä¸­å›½å«è§†é¢‘é“/,+1p' CNTV1.m3u
          cat ipv4.m3u > CNTV2.m3u && sed -i -n '/â˜˜ï¸æ¹–åŒ—æœ¬åœ°é¢‘é“/,+1p' CNTV2.m3u
          cat ipv4.m3u > CNTV3.m3u && sed -i -n '/ğŸå…¨å›½åœ°æ–¹é¢‘é“/,+1p' CNTV3.m3u
          rm -f tsds.m3u && wget https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/refs/heads/main/merged_output.m3u -O tsds.m3u
          cat tsds.m3u > CNTV4.m3u && sed -i -n '/ç”µå½±é¢‘é“/,+1p' CNTV4.m3u
          sed -i 's/ç”µå½±é¢‘é“/ğŸ¬ä¸­å›½ç”µå½±é¢‘é“/' CNTV4.m3u
          cat tsds.m3u > CNTV5.m3u && sed -i -n '/æˆæ›²é¢‘é“/,+1p' CNTV5.m3u
          sed -i 's/æˆæ›²é¢‘é“/ğŸ’ƒä¸­å›½æˆæ›²é¢‘é“/' CNTV5.m3u
          cat tsds.m3u > CNTV6.m3u && sed -i -n '/ğŸ’“ä¸“äº«æºğŸ…±ï¸/,+1p' CNTV6.m3u
          sed -i 's/ğŸ’“ä¸“äº«æºğŸ…±ï¸/ğŸ’°ä»˜è´¹ä¸“äº«é¢‘é“/' CNTV6.m3u
          cat tsds.m3u > CNTV7.m3u && sed -i -n '/ğŸ’“å„¿ç«¥ä¸“äº«/,+1p' CNTV7.m3u
          sed -i 's/ğŸ’“å„¿ç«¥ä¸“äº«/ğŸ‘¶å„¿ç«¥ä¸“äº«é¢‘é“/' CNTV7.m3u
          cat tsds.m3u > CNTV8.m3u && sed -i -n '/æ˜¥æ™š/,+1p' CNTV8.m3u
          sed -i 's/æ˜¥æ™š/ğŸ“€å†å±Šæ˜¥æ™šé¢‘é“/' CNTV8.m3u
          cat CNTV1.m3u >> CNTV.m3u
          cat CNTV2.m3u >> CNTV.m3u
          cat CNTV3.m3u >> CNTV.m3u
          cat CNTV4.m3u >> CNTV.m3u
          cat CNTV5.m3u >> CNTV.m3u
          cat CNTV6.m3u >> CNTV.m3u
          cat CNTV7.m3u >> CNTV.m3u
          cat CNTV8.m3u >> CNTV.m3u
          echo "" >> CNTV.m3u
          rm -f CNTV1.m3u CNTV2.m3u CNTV3.m3u CNTV4.m3u CNTV5.m3u CNTV6.m3u CNTV7.m3u CNTV8.m3u ipv4.m3u zbds.m3u tsds.m3u
          sed -i '/^\s*$/d' CNTV.m3u
          
          # æ•´åˆæº
          cat CCTV.m3u > iptv4.m3u
          cat CNTV.m3u >> iptv4.m3u
          sed -i '/#EXTM3U/d' iptv4.m3u
          sed -i '1i #EXTM3U x-tvg-url="https://live.kilvn.com/epg.xml.gz,https://e.erw.cc/all.xml.gz,http://epg.51zmt.top:8000/e.xml.gz" catchup="append" catchup-source="?playseek=${(b)yyyyMMddHHmmss}-${(e)yyyyMMddHHmmss}"' iptv4.m3u
          sed -i 's|"https://raw.githubusercontent.com|"https://github.moeyy.xyz/https://raw.githubusercontent.com|g' iptv4.m3u
          sed -i '/^\s*$/d' iptv4.m3u

          # å¤§äººæº
          rm -f Adult.m3u && wget http://adultiptv.net/chs.m3u -O Adult.m3u
          sed -i -n '/XXX/,+1p' Adult.m3u
          sed -i 's/XXX/ç¦åˆ©é¢‘é“/' Adult.m3u
          sed -i 's/AdultIPTV.net //g' Adult.m3u
          sed -i '/^\s*$/d' Adult.m3u
          
          cat iptv4.m3u > iptv4+.m3u
          cat Adult.m3u >> iptv4+.m3u
          sed -i '/^\s*$/d' iptv4+.m3u
          
          rm -f CCTV.m3u CNTV.m3u Adult.m3u

          # FMæº
          rm -f radio.m3u && wget https://raw.githubusercontent.com/huangsuming/iptv/main/list/radio.txt -O radio.m3u
          
          # èŠ‚ç›®æº
          rm -f epg.xml && wget https://epg.112114.xyz/pp.xml -O epg.xml

          sed -i 's/ä¸­å›½æ•™è‚²1å°/CETV-1/g' epg.xml
          sed -i 's/ä¸­å›½æ•™è‚²2å°/CETV-2/g' epg.xml
          sed -i 's/ä¸­å›½æ•™è‚²3å°/CETV-3/g' epg.xml
          sed -i 's/ä¸­å›½æ•™è‚²4å°/CETV-4/g' epg.xml
          sed -i '/<channel id="ä¸­å›½æ•™è‚²ä¸€å¥—">/,/<\/channel>/d; /<programme channel="ä¸­å›½æ•™è‚²ä¸€å¥—".*>/,/<\/programme>/d' epg.xml
          
          rm -f epg.xml.gz && gzip -k epg.xml
          
          # README
          sed -i "s/å·²äº [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\} è‡ªåŠ¨æ›´æ–°/å·²äº ${DATE} è‡ªåŠ¨æ›´æ–°/g" README.md

      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout --orphan latest_branch
          git add -A
          git commit -am "${DATE} æ›´æ–°."
          git branch -D ${{ matrix.branch }}
          git branch -m ${{ matrix.branch }}

      - name: Push
        run: git push -f origin ${{ matrix.branch }}
